name: mqd_v1
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.0.0
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  equatable: ^2.0.0
  flutter_login_facebook: ^1.6.2
  google_sign_in: ^5.0.7
  outline_gradient_button: ^2.0.0+1
  pin_code_fields: ^7.3.0
  sms_autofill: ^2.0.0
  pin_input_text_field: 4.1.0
  dotted_border: 2.0.0+3
  readmore: ^2.1.0
  flutter_staggered_grid_view: ^0.4.1
  dio: ^5.0.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Lexend
      fonts: 
        - asset: assets/fonts/LexendSemiBold.ttf
          weight: 600
        - asset: assets/fonts/LexendRegular.ttf
          weight: 400
        - asset: assets/fonts/LexendMedium.ttf
          weight: 500
        - asset: assets/fonts/LexendBold.ttf
          weight: 700
    - family: Sk-Modernist
      fonts: 
        - asset: assets/fonts/SkModernistRegular.ttf
          weight: 400
        - asset: assets/fonts/SkModernistBold.ttf
          weight: 700
    - family: Lato
      fonts: 
        - asset: assets/fonts/LatoMedium.ttf
          weight: 500
